name: lemmatizerx
description: Lemmatizer for text in English. Inspired by Python's nltk.corpus.reader.wordnet.morphy
version: 0.0.1
repository: https://github.com/xErik/lemmatizerx
issue_tracker: https://github.com/xErik/lemmatizerx/issues

executables:
  lemma:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.8.1
  test: ^1.21.1

 